apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-template
  labels:
    app.kubernetes.io/name: webapp-template
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp-template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp-template
    spec:
      containers:
        - name: webapp-template
          envFrom:
            - secretRef:
                name: secret
            - configMapRef:
                name: config
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-template
spec:
  selector:
    app.kubernetes.io/name: webapp-template
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: udp
      protocol: UDP
      port: 80
      targetPort: 3000
