apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: treasure-hunt
spec:
  parentRefs:
    - kind: Gateway
      name: nginx-production-gateway
      namespace: nginx-production-gateway
  hostnames:
    - hunters.visoft.dev
  rules:
    - matches:
      backendRefs:
        - name: treasure-hunt
          port: 80
