apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webapp-template
spec:
  parentRefs:
    - kind: Gateway
      name: nginx-staging-gateway
      namespace: nginx-staging-gateway
  hostnames:
    - test.staging.visoft.dev
  rules:
    - matches:
      backendRefs:
        - name: webapp-template
          port: 80
