---
- name: Setup Cert-Manager
  hosts: localhost

  tasks:
    - name: Install Cert-Manager Helm chart
      kubernetes.core.helm:
        name: cert-manager
        namespace: cert-manager
        chart_ref: cert-manager
        chart_repo_url: https://charts.jetstack.io
        atomic: true
        create_namespace: true
        wait: true
        values: "{{ lookup('file', '../resources/values/cert-manager.yaml') | from_yaml }}"
